version: '3'

services:
  hgbr_container:
    container_name: hgbr
    build:
      context: .
      dockerfile: Dockerfile
    image: hgbr
    restart: always
    volumes:
      - ../../:/App
      - /home/burgunder/WINGS/Datasets/Fairness/split_quad/ds quad:/Data
    entrypoint: tail -f /dev/null
