FROM python:3.6

RUN apt update -y && apt install -y sudo wget \
    && addgroup --gid 1000 user \
    && adduser --disabled-password --gecos '' --uid 1000 --gid 1000 user \
    && usermod -aG sudo user \
    && echo "user ALL=(ALL) NOPASSWD:ALL" >> /etc/sudoers \
    && pip install jupyter pipreqs

RUN sudo apt-get install -y libssl-dev libcurl4-openssl-dev libyaml-dev build-essential libopenblas-dev libcap-dev ffmpeg git
RUN git clone https://github.com/datamllab/tods.git \
    && cd tods && pip install -e .


COPY requirements.txt requirements.txt
RUN pip install -r requirements.txt


USER user
WORKDIR /App
